spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_db
    driver-class-name: org.postgresql.Driver
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect