spring:
  profiles:
    active: test
  api:
    url: ${TMDB_API_URL}
server:
  servlet:
    context-path: /api/v1
jwt:
  secret: ${JWT_SECRET}
app:
  upload:
    path: D:\ProjectsImageRepo\profilePics\